version: "3.8"
services:
  qbit-orphaned-downloads:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - INCLUDE_CATEGORY=movies,tv
      - OMIT_CATEGORY=
      - OMIT_TAGS=autobrr
      - ORPHAN_TAG=orphan
      - QBIT_HOST=http://qbittorrent:31493
      - QBIT_USERNAME=admin
      - QBIT_PASSWORD=Jm12345
      - INTERVAL_HOURS=0.001
    volumes:
      - /srv/data:/media:ro
      - ./index.js:/app/index.js
    networks:
      - beelink
networks:
  beelink:
    external: true
